apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: stat
type: Opaque
stringData:
  mysql-root-password: RootPass!123
  mysql-replication-user: repl
  mysql-replication-password: ReplPass!123
