 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
  labels:
    app: mysql
    pod-index: "0"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/mysql-demo/mysql-0
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  labels:
    app: mysql
    pod-index: "1"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/mysql-demo/mysql-1
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2
  labels:
    app: mysql
    pod-index: "2"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/mysql-demo/mysql-2
    type: DirectoryOrCreate
