apiVersion: v1
kind: Pod
metadata:
  name: pvctest-pod2
  namespace: ns-1

spec:
  containers:
  - name: cont1
    image: busybox
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: teststorage

  volumes:
  - name: teststorage
    persistentVolumeClaim:
      claimName: pvc-hvy
