apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
  namespace: ns-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
