apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo

spec:
  containers:
  - name: cont1
    image: ubuntu
    command: ["/bin/bash","-c","while true;do echo welcome to ust class;sleep 5;done"]
    volumeMounts:
    - name: sharedvol
      mountPath: "/temp/container1"

  - name: cont2
    image: ubuntu
    command: ["/bin/bash","-c","while true;do echo welcome to training class;sleep 6;done"]
    volumeMounts:
    - name: sharedvol
      mountPath: "/temp/container2"

  volumes:
  - name: sharedvol
    emptyDir: {}
