apiVersion: v1
kind: Pod
metadata:
  name: pod-nopvc
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc-notexisting
