apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nfs-pod

  template:
    metadata:
      labels:
        app: nfs-pod
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh","-c","while true; do echo 'Persistent Data' >> /data/file.txt; sleep 10; done"]

          volumeMounts:
            - name: nfs
              mountPath: /data

      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
