apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-dy

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-class
  resources:
    requests:
      storage: 200Mi
