apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  USER_SERVICE_URL: "http://user-service:3001"
  ACCOUNT_SERVICE_URL: "http://account-service:3002"
  TRANSACTION_SERVICE_URL: "http://transaction-service:3003"
