apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
type: Opaque
stringData:
  db-password: "bankpass"
  jwt-secret: "banking_jwt_chriss"
  internal-api-key: "internal_secret_key_production"
