apiVersion: v1
kind: Pod
metadata:
  name: testyaml
  labels:
    app: ustimage
  namespace: res
spec:
  containers:
  - name: nginx1
    image: rajcosivadevops/ustimage:latest
    ports:
      - containerPort: 80


