apiVersion: v1
kind: Pod
metadata:
  name: affinity-gt
  namespace: scheduling-demo
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: generation
            operator: Gt
            values:
            - "2"
