apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: debug

spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh","-c","sleep 3600"]
  restartPolicy: Never
