apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentexample
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: cont1
        image: hashicorp/http-echo:1.0
        args:
        - "-text=Hello from kubernetes version2"
        ports:
        - containerPort: 5678

