apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetexample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: cstay
      labels:
        app: myapp
    spec:
      containers:
      - name: frontendcont
        image: neerajbala/cstay:frontendv1
        ports:
        - containerPort: 80
