apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      restartPolicy: Always

      containers:
      - name: mysql
        image: mysql:8

        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root

        - name: MYSQL_DATABASE
          value: my_db

        - name: MYSQL_USER
          value: appuser

        - name: MYSQL_PASSWORD
          value: "password"

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 5

      volumes:
      - name: mysql-storage
        emptyDir: {}
